AWSTemplateFormatVersion: '2010-09-09'
Description: Java application deployment on EC2 using GitHub Actions OIDC (No IAM creation)

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 key pair name

  ArtifactBucket:
    Type: String
    Description: S3 bucket where the application JAR is stored

Resources:
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and application access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0fc5d935ebf8bc3bc  # Amazon Linux 2023 (us-east-1)
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -x
          yum update -y
          yum install -y java-17-amazon-corretto awscli
          cd /home/ec2-user
          aws s3 cp s3://${ArtifactBucket}/demo-0.0.1-SNAPSHOT.jar demo-0.0.1-SNAPSHOT.jar
          chmod 755 demo-0.0.1-SNAPSHOT.jar
          nohup java -jar demo-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
